
var Products =
  [
    {
      "product_id": "1",
      "title": "Brown eggs",
      "category": "Dairy",
      "description": "Raw organic brown eggs in a basket",
      "price": 28.1,
      "rating": 4,
      "img_url": "Images/biscuit-packet.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "2",
      "title": "Sweet fresh stawberry",
      "category": "fruit",
      "description": "Sweet fresh stawberry on the wooden table",
      "price": 28.1,
      "rating": 4,
      "img_url": "Images/biscuit-packet.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "3",
      "title": "Yogurt",
      "category": "dairy",
      "description": "Homemade yogurt with raspberry and mint",
      "price": 28.1,
      "rating": 4,
      "img_url": "Images/biscuit-packet.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "4",
      "title": "Sandwich with salad",
      "category": "vegetable",
      "description": "Vegan sandwich with salad, tomato and radish",
      "price": 28.1,
      "rating": 4,
      "img_url": "Images/biscuit-packet.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "5",
      "title": "Cherry",
      "category": "fruit",
      "description": "Cherry with sugar on old table",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "6",
      "title": "Raw asparagus",
      "category": "vegetable",
      "description": "Raw fresh asparagus salad with cheese and dressing",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "7",
      "title": "Corn",
      "category": "vegetable",
      "description": "Grilled corn on the cob with salt and butter",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "8",
      "title": "Fresh blueberries",
      "category": "fruit",
      "description": "Healthy breakfast. berry crumble with fresh blueberries, raspberries, strawberries, almond, walnuts, pecans, yogurt, and mint in ceramic plates over white wooden surface, top view",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "9",
      "title": "Smashed avocado",
      "category": "fruit",
      "description": "Vegan sandwiches with smashed avocado, tomatoes and radish. top view",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "10",
      "title": "Italian ciabatta",
      "category": "bakery",
      "description": "Italian ciabatta bread cut in slices on wooden chopping board with herbs, garlic and olives over dark grunge backdrop, top view",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "11",
      "title": "Rustic breakfast",
      "category": "dairy",
      "description": "Rustic healthy breakfast set. cooked buckwheat groats with milk and honey on dark grunge backdrop. top view, copy space",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "12",
      "title": "Sliced lemons",
      "category": "fruit",
      "description": "Heap of whole and sliced lemons and limes with mint in vintage metal grid box over old wooden table with turquoise wooden background. dark rustic style.",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "13",
      "title": "Plums",
      "category": "fruit",
      "description": "Yellow and red sweet plums",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "14",
      "category": "Strawberries",
      "type": "fruit",
      "description": "Healthy breakfast set. rice cereal or porridge with fresh strawberry, apricots, almond and honey over white rustic wood backdrop, top view, \u0000",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "15",
      "title": "Tomatoes",
      "category": "fruit",
      "description": "Organic tomatoes made with love",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "16",
      "title": "Basil",
      "category": "vegetable",
      "description": "Concept of vegan food with basil",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "17",
      "title": "Peaches on branch",
      "category": "fruit",
      "description": "Peaches on branch with leaves and glasses with peach juice and limonade with ice cubes in aluminum tray over old metal table. dark rustic style. top view.",
      "price": 28.1,
      "rating": 4,
      "img_url":"Images/biscuit-packet.png",
      "quantity" : 1,
      "discount_price": "",
    }]