
var Products =
  [
    {
      "product_id": "1",
      "title": "LAYS SALTED",
      "category": "Grocery",
      "description": "Original salted flavour",
      "price": 180.00,
      "rating": 4,
      "img_url": "Images/lays.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "2",
      "title": "FRESH STRAWBERRIES",
      "category": "Grocery",
      "description": "Sweet fresh stawberries",
      "price": 350.00,
      "rating": 4,
      "img_url": "Images/strawberry.png",
      "quantity": 1,
      "discount_price": 350.00,
    },
    {
      "product_id": "3",
      "title": "KRAFT CHEESE",
      "category": "Dairy",
      "description": "Soft cheddar cheese",
      "price": 420.00,
      "rating": 4,
      "img_url": "Images/cheese.png",
      "quantity": 1,
      "discount_price": 400.00,
    },
    {
      "product_id": "4",
      "title": "BANANA NUT CHEERIOS",
      "category": "Grocery",
      "description": "Whole grain oats and fresh banana",
      "price": 280.00,
      "rating": 4,
      "img_url": "Images/cheerios.png",
      "quantity": 1,
      "discount_price": "",
    },
    {
      "product_id": "5",
      "title": "STRAWBERRY JAM",
      "category": "Canned goods & soups",
      "description": "Family farmer owned natural strawberry spread",
      "price": 300.00,
      "rating": 4,
      "img_url":"Images/jam.png",
      "quantity" : 1,
      "discount_price": 280.00,
    },
    {
      "product_id": "6",
      "title": "COCONUT",
      "category": "Grocery",
      "description": "Fresh Coconut",
      "price": 65.00,
      "rating": 4,
      "img_url":"Images/coconut.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "7",
      "title": "CORN COB",
      "category": "Grocery",
      "description": "Homegrown fresh corn",
      "price": 80.00,
      "rating": 4,
      "img_url":"corn.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "8",
      "title": "LIFEBUOY HANDWASH",
      "category": "HEALTH & BEAUTY",
      "description": "Lifebuoy cool fresh lemon scented ",
      "price": 120.00,
      "rating": 4,
      "img_url":"Images/handwash.png",
      "quantity" : 1,
      "discount_price": 90.00,
    },
    {
      "product_id": "9",
      "title": "KOTTU MEE NOODLES",
      "category": "Grocery",
      "description": "Hot and Spicy chicken flavoured",
      "price": 80.00,
      "rating": 4,
      "img_url":"Images/noodles.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "10",
      "title": "KNORR PASTA",
      "category": "Grocery",
      "description": "Fusilli pasta with broccoli and cheesy sauce",
      "price": 280.00,
      "rating": 4,
      "img_url":"Images/sausages.png",
      "quantity" : 1,
      "discount_price": 250.00,
    },
    {
      "product_id": "11",
      "title": "LUX MAGICAL BEAUTY SOAP",
      "category": "Health & Beauty",
      "description": "For a long lasting enchanting fragnance",
      "price": 60.00,
      "rating": 4,
      "img_url":"Images/Lux.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "12",
      "title": "PORK SAUSAGES",
      "category": "Meats & Seafood",
      "description": "Premium birchwood smoked sausages",
      "price": 280.00,
      "rating": 4,
      "img_url":"Images/sausages.png",
      "quantity" : 1,
      "discount_price": 250.00,
    },
    {
      "product_id": "13",
      "title": "BROCCOLI",
      "category": "Grocery",
      "description": "Fresh farm grown broccoli",
      "price": 130.00,
      "rating": 4,
      "img_url":"Images/broccoli.png",
      "quantity" : 1,
      "discount_price": 100.00,
    },
    {
      "product_id": "14",
      "title": "SIGNAL TOOTHPASTE",
      "category": "Health & Beauty",
      "description": "Pro sensitive relief and repair",
      "price": 100.00,
      "rating": 4,
      "img_url":"Images/toothpaste.png",
      "quantity" : 1,
      "discount_price": "",
    },
    {
      "product_id": "15",
      "title": "SHAFER RED WINE",
      "category": "Spirits & Wines",
      "description": "2007 Napa Valley Stags Leap District",
      "price": 2850.00,
      "rating": 4,
      "img_url":"Images/wine.png",
      "quantity" : 1,
      "discount_price": 2500.00,
    },
    {
      "product_id": "16",
      "title": "CAMPBELLS SOUP",
      "category": "Canned goods & soups",
      "description": "Minestrone with italian sausage",
      "price": 280,
      "rating": 4,
      "img_url":"Images/soup.png",
      "quantity" : 1,
      "discount_price": 250,
    },
    {
      "product_id": "17",
      "title": "SPRITE BOTTLE",
      "category": "Grocery",
      "description": "Fizzy drink",
      "price": 300.00,
      "rating": 4,
      "img_url":"Images/sprite.png",
      "quantity" : 1,
      "discount_price": 270.00,
    }]
