var Promotions =
    [
        {
            "promotion_id": "1",
            "title": "COMFORT BUNDLE PACK",
            "category": "Popular",
            "description": "Buy a Comfort fabric conditioner and get another free",
            "price": 400.00,
            "terms": "*This promotion is valid only until the 18th of January 2020.",
            "img_url": "Images/Comfort bundle.jpg",
            "quantity": 1,
        },
        {
            "promotion_id": "2",
            "title": "MILK BUNDLE PROMOTION",
            "category": "Popular",
            "description": "Buy a Highland Vanilla flavoured milk packet and get a free Highland Plain Milk Packet",
            "price": 720.00,
            "terms": "*This promotion is valid only until the 31st of December 2019.",
            "img_url": "Images/milk-packet-png-1.png",
            "quantity": 1,
        },

        {
            "promotion_id": "3",
            "title": "MORNING NECESSITIES",
            "category": "Personalized",
            "description": "Receive a personalized collection of cereals and hot beverage items at a lower rate",
            "price": 2300.00,
            "terms": "*This promotion is valid only until the 25th of December 2019.",
            "img_url": "Images/Breakfast promotion.png",
            "quantity": 1,
        },
        {
            "promotion_id": "4",
            "title": "VIM BUNDLE PACK",
            "category": "Ending soon",
            "description": "Buy a Vim dishwash soap and get another free",
            "price": 700.00,
            "terms": "*This promotion is valid only until the 13th of February 2020.",
            "img_url": "Images/Vim bundle pack.jpg",
            "quantity": 1,
        },
        {
            "promotion_id": "5",
            "title": "REWARD HAMPER",
            "category": "Personalized",
            "description": "Enjoy a hamper full of goodies worth enjoying this season",
            "price": 3000.00,
            "terms": "*This promotion is valid only until the 25th of December 2019.",
            "img_url": "Images/many-promotion.jpg",
            "quantity": 1,
        },
        {
            "promotion_id": "6",
            "title": "BAKERY GOODNESS",
            "category": "Ending soon",
            "description": "Receive a baking tray with a purchase of selected bakery items",
            "price": 500.00,
            "terms": "*This promotion is valid only until the 15th of December 2019.",
            "img_url": "Images/Bakery_promo.jpg",
            "quantity": 1,
        },
    ]